basic_app/urls.py
from django.urls import path, include
from basic_app import views

# This is the name we use in the templates to call the urls
app_name='basic_app'

urlpatterns = [
    path('', views.SchoolListView.as_view(), name='list'),
    path('create/', views.SchoolCreateView.as_view(), name='create'),
    path('<slug:pk>/', views.SchoolDetailView.as_view(), name='detail'),
    path('update/<slug:pk>/', views.SchoolUpdateView.as_view(), name='update'),
    path('delete/<slug:pk>/', views.SchoolDeleteView.as_view(), name='delete'),
]

django_class_views/urls.py
from django.contrib import admin
from django.urls import path, include
from basic_app import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.IndexView.as_view(), name='index'),
    path('basic_app/', include('basic_app.urls', namespace='basic_app'))
]

basic_app/models.py
from django.db import models
from django.urls.base import reverse

# Create your models here.
class School(models.Model):
  name = models.CharField(max_length=256)
  principal = models.CharField(max_length=256)
  location = models.CharField(max_length=256)

  def __str__(self):
    return self.name

  def get_absolute_url(self):
    return reverse("basic_app:detail", kwargs={"pk": self.pk})

class Student(models.Model):
  name = models.CharField(max_length=256)
  age = models.PositiveIntegerField()
  # Related name should be in plural :(
  school = models.ForeignKey(School,related_name='student', on_delete=models.CASCADE)

  def __str__(self):
    return self.name

basic_app/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import (View, TemplateView,
                                  ListView, DetailView,
                                  CreateView, UpdateView,
                                  DeleteView)
from . import models

class IndexView(TemplateView):
  template_name = 'index.html'

  def get_context_data(self, **kwargs):
    context = super().get_context_data(**kwargs)
    context['injectme'] = 'BASIC INJECTION!'
    return context

class SchoolListView(ListView):
  context_object_name = 'schools' # use this if you want to give a custom name to the generated list
  model = models.School
  # it generates school_list by default

class SchoolDetailView(DetailView):
  context_object_name = 'school_detail' # use this if you want to give a custom name to the generated detail
  model = models.School
  template_name = 'basic_app/school_detail.html'
  # it generates school by default

class SchoolCreateView(CreateView):
  fields = ('name', 'principal', 'location')
  model = models.School

class SchoolUpdateView(UpdateView):
  fields = ('name', 'principal')
  model = models.School

class SchoolDeleteView(DeleteView):
  model = models.School
  success_url = reverse_lazy('basic_app:list')

basic_app/templates/basic_app/basic_app_base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Base</title>
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'basic_app:list' %}">Schools</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <a class="nav-link" href="{% url 'admin:index' %}">Admin</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'admin:index' %}">Register</a>
            </li>
          </ul>
        </div>
      </div>
    </nav>
    <div class='container'>
      {% block body_block %}

      {% endblock body_block %}
    </div>
  </body>
</html>

basic_app/templates/basic_app/school_confirm_delete.html
{% extends 'basic_app/basic_app_base.html' %}

{% block body_block %}
  <div class='jumbotron'>
    <h1>Delete {{school.name}}? </h1>

    <form method='post'>
      {% csrf_token %}
      <input type='submit' class='btn btn-danger' value='Delete' >
      <a href="{% url 'basic_app:detail' pk=school.pk %}">Cancel</a>
    </form>
{% endblock body_block %}

basic_app/templates/basic_app/school_detail.html
{% extends 'basic_app/basic_app_base.html' %}

{% block body_block %}
  <div class='jumbotron'>
    <h1>Welcome to the school detail page!</h1>

    <h2>School details:</h2>
    <p>Name: {{school_detail.name}}</p>
    <p>Principal: {{school_detail.principal}}</p>
    <p>Location: {{school_detail.location}}</p>

    <h3>Students:</h3>
    {% for student in school_detail.student.all %}
      <p>Name: {{student.name}}</p>
      <p>Age: {{student.age}}</p>
    {% endfor %}
  </div>

  <div class='container'>
    <p>
      <a class='btn btn-warning' href="{% url 'basic_app:update' pk=school_detail.pk %}">Update</a>
    </p>
  </div>
{% endblock body_block %}

basic_app/templates/basic_app/school_form.html
{% extends 'basic_app/basic_app_base.html' %}

{% block body_block %}
  <div class='jumbotron'>
    <h1>
      {% if not form.instance.pk %}
        Create School
      {% else %}
        Update School
      {% endif %}
    </h1>

    <form method='post'>
      {% csrf_token %}
      {{ form.as_p }}
      <input type='submit' class='btn btn-primary' value='Submit' >
    </form>
{% endblock body_block %}

basic_app/templates/basic_app/school_list.html
{% extends 'basic_app/basic_app_base.html' %}

{% block body_block %}
  <div class='jumbotron'>
    <h1>Welcome to a list of all the schools!</h1>
    <ol>
      {% for school in schools %}
        <h2>
          <li>
            <a href="{{school.id}}">
              {{school.name}}
            </a>
          </li>
        </h2>
      {% endfor %}
    </ol>
  </div>
{% endblock body_block %}

templates/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Base</title>
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'basic_app:list' %}">Schools</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <a class="nav-link" href="{% url 'admin:index' %}">Admin</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'admin:index' %}">Register</a>
            </li>
          </ul>
        </div>
      </div>
    </nav>
    <div class='container'>
      {% block body_block %}

      {% endblock body_block %}
    </div>
  </body>
</html>

templates/index.html
{% extends 'base.html' %}

{% block body_block %}
  <div class='jumbotron'>
    <h1>Home Page!</h1>
  </div>
{% endblock body_block %}